### ISSUE TITLE
Can't convert cue/bin-image if work-directory is not set to source-file-location

### ISSUE THREAD

**Issue by Switch123456789** [claunia/DiscImageChef#838] opened 2024-03-11 22:00 UTC
### Version

6.0.0~alpha9+4825d414.4825d414604fe30e23ceabc169be94f

### Tested debug version?

Yes

### Which operating systems have you used?

Linux

### What is the architectural bit size you're using?

64-bit

### What processor are you using?

AMD

### Image format

cue/bin

### Application that created the image

aaru

### What were you doing when it failed?

I was converting the image to another format...

### Destination image format

ccd

### Filesystem

ext4

### Description

If I convert a cue/bin-image, aaru can't find the bin-files referenced within the cue-sheet unless the work-directory is where the cue-file is located.

### Exact command line used

aaru image convert "path/to/source.cue" "path/to/destination.ccd"

### Expected behavior

Aaru can find the bin-files and converts the image successfully. 

### Actual behavior

Aaru can't find the bin-files and therefor can't convert the image. 

### Output of command execution with debug output enabled

```shell
DEBUG (Convert-image command): --cicm-xml=
DEBUG (Convert-image command): --comments=
DEBUG (Convert-image command): --count=64
DEBUG (Convert-image command): --creator=
DEBUG (Convert-image command): --debug=True
DEBUG (Convert-image command): --drive-manufacturer=
DEBUG (Convert-image command): --drive-model=
DEBUG (Convert-image command): --drive-revision=
DEBUG (Convert-image command): --drive-serial=
DEBUG (Convert-image command): --force=False
DEBUG (Convert-image command): --format=
DEBUG (Convert-image command): --geometry=
DEBUG (Convert-image command): --input=/home/switch/DESKTOP/gta/disk1/disk1.cue
DEBUG (Convert-image command): --media-barcode=
DEBUG (Convert-image command): --media-lastsequence=0
DEBUG (Convert-image command): --media-manufacturer=
DEBUG (Convert-image command): --media-model=
DEBUG (Convert-image command): --media-partnumber=
DEBUG (Convert-image command): --media-sequence=0
DEBUG (Convert-image command): --media-serial=
DEBUG (Convert-image command): --media-title=
DEBUG (Convert-image command): --options=
DEBUG (Convert-image command): --output=/home/switch/DESKTOP/gta/disk1/ccd/disk1.ccd
DEBUG (Convert-image command): --resume-file=
DEBUG (Convert-image command): --verbose=False
DEBUG (Convert-image command): --fix-subchannel-position=True
DEBUG (Convert-image command): --fix-subchannel=False
DEBUG (Convert-image command): --fix-subchannel-crc=False
DEBUG (Convert-image command): --generate-subchannels=False
DEBUG (Convert-image command): --decrypt=False
DEBUG (Convert-image command): --aaru-metadata=
DEBUG (Convert-image command): Parsed options:
DEBUG (Format detection): Trying plugin A2R
DEBUG (Format detection): Trying plugin Aaru Format
DEBUG (Format detection): Trying plugin ACT Apricot Disk Image
DEBUG (Format detection): Trying plugin Alcohol 120% Media Descriptor Structure
DEBUG (Format detection): Trying plugin Anex86 Disk Image
DEBUG (Anex86 plugin): fdihdr.unknown = 1162627398
DEBUG (Anex86 plugin): fdihdr.hddtype = 1768170016
DEBUG (Anex86 plugin): fdihdr.hdrSize = 774990707
DEBUG (Anex86 plugin): fdihdr.dskSize = 577661282
DEBUG (Anex86 plugin): fdihdr.bps = 1313423904
DEBUG (Anex86 plugin): fdihdr.spt = 223957569
DEBUG (Anex86 plugin): fdihdr.heads = 1296388618
DEBUG (Anex86 plugin): fdihdr.cylinders = 1397052192
DEBUG (Format detection): Trying plugin Apple 2IMG
DEBUG (Format detection): Trying plugin Apple Disk Archival/Retrieval Tool
DEBUG (Format detection): Trying plugin Apple DiskCopy 4.2
DEBUG (Format detection): Trying plugin Apple New Disk Image Format
DEBUG (Format detection): Trying plugin Apple NIB
DEBUG (Format detection): Trying plugin Apple Universal Disk Image Format
DEBUG (Format detection): Trying plugin Basic Lisa Utility
DEBUG (Format detection): Trying plugin BlindWrite 4
DEBUG (Format detection): Trying plugin BlindWrite 5
DEBUG (Format detection): Trying plugin CDRDAO tocfile
DEBUG (Format detection): Trying plugin CDRWin cuesheet
Input image format identified by CDRWin cuesheet.
DEBUG (CDRWin plugin): Found FILE at line 1
File ""disk1.bin"" not found.
Unable to open image format
Error: ENOENT
```

**Comment by claunia** [comment] 2024-03-11 22:02
Duplicate of #214

**Closed as completed by claunia** 2024-03-11 22:02 UTC
Labels: bug, duplicate, dump image format, needs triage

**Comment by Switch123456789** [comment] 2024-03-11 22:04
> Duplicate of #214

Sorry, I didn't find that one. Thanks for referencing.
